### ISSUE TITLE
目录功能能否向左折叠起来

### ISSUE THREAD

**Issue by jimywu19** [eson-sheng/MARKDOWN_FOR_PHP#1]
可以否增加一个折叠按钮，假如目录条目极少或没有，折叠起来可以更好展示内容

**Comment by eson-sheng** [comment]
ojbk

**Comment by eson-sheng** [comment]
ojbk [825541f](https://github.com/eson-sheng/MARKDOWN_FOR_PHP/commit/825541fec78b9e6df33e7df1a2b0fe73daea4013)
